name: my_env
channels:
  - anaconda
  - dglteam
  - pytorch
  - plotly
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2019.03
  - _libgcc_mutex=0.1
  - alabaster=0.7.12
  - anaconda=custom
  - anaconda-client=1.7.2
  - anaconda-project=0.8.4
  - argh=0.26.2
  - asn1crypto=1.3.0
  - astroid=2.3.3
  - astropy=4.0.1.post1
  - atomicwrites=1.3.0
  - attrs=19.3.0
  - autopep8=1.4.4
  - babel=2.8.0
  - backcall=0.1.0
  - backports=1.0
  - backports.os=0.1.1
  - backports.shutil_get_terminal_size=1.0.0
  - beautifulsoup4=4.8.2
  - bitarray=1.2.1
  - bkcharts=0.2
  - blas=1.0
  - bleach=3.1.0
  - blosc=1.16.3
  - bokeh=2.0.1
  - boost-cpp=1.69.0
  - boto=2.49.0
  - bottleneck=1.3.2
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - cairo=1.14.12
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - cgal-cpp=4.14
  - chardet=3.0.4
  - chart-studio=1.1.0
  - click=7.1.1
  - cloudpickle=1.3.0
  - clyent=1.2.2
  - colorama=0.4.3
  - contextlib2=0.6.0.post1
  - cpuonly=1.0
  - cryptography=2.8
  - curl=7.69.1
  - cycler=0.10.0
  - cython=0.29.15
  - cytoolz=0.10.1
  - dask=2.14.0
  - dask-core=2.14.0
  - dbus=1.13.12
  - decorator=4.4.2
  - defusedxml=0.6.0
  - dgl=0.4.2
  - diff-match-patch=20181111
  - distributed=2.14.0
  - docutils=0.16
  - eigen=3.3.7
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - expat=2.2.6
  - fastcache=1.1.0
  - ffmpeg=4.0
  - filelock=3.0.12
  - flake8=3.7.9
  - flask=1.1.1
  - fontconfig=2.13.0
  - freeglut=3.0.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - fsspec=0.7.1
  - future=0.18.2
  - get_terminal_size=1.0.0
  - gevent=1.4.0
  - glib=2.63.1
  - glob2=0.7
  - gmp=6.1.2
  - gmpy2=2.0.8
  - graphite2=1.3.13
  - greenlet=0.4.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gudhi=2.3.0
  - h5py=2.8.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - heapdict=1.0.1
  - html5lib=1.0.1
  - hypothesis=5.5.4
  - icu=58.2
  - idna=2.9
  - imageio=2.8.0
  - imagesize=1.2.0
  - importlib_metadata=1.5.0
  - intel-openmp=2019.4
  - intervaltree=3.0.2
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - itsdangerous=1.1.0
  - jasper=2.0.14
  - jbig=2.1
  - jdcal=1.4.1
  - jedi=0.15.2
  - jeepney=0.4.3
  - jinja2=2.11.1
  - joblib=0.14.1
  - jpeg=9b
  - json5=0.9.4
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.2
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - jupyterlab=1.2.6
  - jupyterlab_server=1.1.0
  - keyring=21.1.1
  - kiwisolver=1.1.0
  - krb5=1.17.1
  - lazy-object-proxy=1.4.3
  - libarchive=3.3.3
  - libcurl=7.69.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - liblief=0.9.0
  - libopencv=3.4.2
  - libopus=1.3
  - libpng=1.6.37
  - libsodium=1.0.16
  - libspatialindex=1.9.3
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libtool=2.4.6
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.9
  - libxslt=1.1.33
  - llvmlite=0.31.0
  - locket=0.2.0
  - lxml=4.5.0
  - lz4-c=1.8.1.2
  - lzo=2.10
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.2.0
  - mpc=1.1.0
  - mpfr=4.0.1
  - mpmath=1.1.0
  - msgpack-python=1.0.0
  - multipledispatch=0.6.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.2
  - networkx=2.3
  - ninja=1.9.0
  - nltk=3.4.5
  - nose=1.3.7
  - notebook=6.0.3
  - numba=0.48.0
  - numexpr=2.7.1
  - numpy-base=1.18.1
  - numpydoc=0.9.2
  - olefile=0.46
  - opencv=3.4.2
  - openpyxl=3.0.3
  - openssl=1.1.1f
  - packaging=20.3
  - pandas=1.0.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.5.2
  - partd=1.1.0
  - patchelf=0.10
  - path=13.1.0
  - path.py=12.4.0
  - pathlib2=2.3.5
  - pathtools=0.1.2
  - patsy=0.5.1
  - pcre=8.43
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - pixman=0.38.0
  - pkginfo=1.5.0.1
  - pluggy=0.13.1
  - ply=3.11
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - psutil=5.7.0
  - ptyprocess=0.6.0
  - py=1.8.1
  - py-lief=0.9.0
  - py-opencv=3.4.2
  - pycodestyle=2.5.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pycrypto=2.6.1
  - pycurl=7.43.0.5
  - pydocstyle=4.0.1
  - pyflakes=2.1.1
  - pygments=2.6.1
  - pylint=2.4.4
  - pyodbc=4.0.30
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - pytables=3.4.4
  - pytest=5.4.1
  - pytest-arraydiff=0.3
  - pytest-astropy=0.8.0
  - pytest-astropy-header=0.1.2
  - pytest-doctestplus=0.5.0
  - pytest-openfiles=0.4.0
  - pytest-remotedata=0.3.2
  - python=3.7.4
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.3.4
  - python-language-server=0.31.9
  - python-libarchive-c=2.8
  - pytorch=1.2.0
  - pytz=2019.3
  - pywavelets=1.1.1
  - pyxdg=0.26
  - pyyaml=5.3.1
  - pyzmq=18.1.1
  - qdarkstyle=2.8
  - qt=5.9.7
  - qtawesome=0.7.0
  - qtconsole=4.7.2
  - qtpy=1.9.0
  - readline=7.0
  - requests=2.23.0
  - retrying=1.3.3
  - rope=0.16.0
  - rtree=0.9.3
  - ruamel_yaml=0.15.87
  - scikit-image=0.16.2
  - scipy=1.3.1
  - seaborn=0.10.0
  - secretstorage=3.1.2
  - send2trash=1.5.0
  - setuptools=46.1.3
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.19.8
  - six=1.14.0
  - snappy=1.1.7
  - snowballstemmer=2.0.0
  - sortedcollections=1.1.2
  - sortedcontainers=2.1.0
  - soupsieve=2.0
  - sphinx=2.4.4
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sphinxcontrib-websupport=1.2.1
  - spyder=4.1.2
  - spyder-kernels=1.9.0
  - sqlalchemy=1.3.15
  - sqlite=3.31.1
  - statsmodels=0.11.0
  - sympy=1.5.1
  - tbb=2020.0
  - tblib=1.6.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - toolz=0.10.0
  - torchvision=0.4.0
  - tornado=6.0.4
  - tqdm=4.44.1
  - traitlets=4.3.3
  - typing_extensions=3.7.4.1
  - ujson=1.35
  - unicodecsv=0.14.1
  - unixodbc=2.3.7
  - urllib3=1.25.8
  - watchdog=0.10.2
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - werkzeug=1.0.0
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - wurlitzer=2.0.0
  - xlrd=1.2.0
  - xlsxwriter=1.2.8
  - xlwt=1.3.0
  - xz=5.2.4
  - yaml=0.1.7
  - yapf=0.28.0
  - zeromq=4.3.1
  - zict=2.0.0
  - zipp=2.2.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - connected-components-3d==1.6.0
    - giotto-learn==0.1.0
    - giotto-tda==0.2.2
    - giotto-time==0.2.1
    - hopcroftkarp==1.2.4
    - jplephem==2.14
    - kmapper==1.2.0
    - lunardate==0.2.0
    - numpy==1.17.3
    - numpy-stl==2.11.2
    - persim==0.1.1
    - plotly==4.5.4
    - pycalverter==1.6.1
    - pyflagser==0.4.0
    - pyluach==1.0.1
    - python-igraph==0.8.0
    - python-utils==2.4.0
    - ripser==0.4.1
    - scikit-learn==0.22.2.post1
    - sgp4==2.7
    - simplicial==0.6.2
    - skyfield==1.20
    - skyfield-data==0.1.0
    - texttable==1.6.2
    - vtk==8.1.2
    - workalendar==9.0.0

